"""empty message

Revision ID: 49cee92ff65d
Revises: 7b341695f43f
Create Date: 2022-11-05 14:25:45.482293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cee92ff65d'
down_revision = '7b341695f43f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviewer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tag', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=350), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['interviewer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dislikes',
    sa.Column('interviewer_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interviewer_id'], ['interviewer.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('interviewer_id', 'question_id')
    )
    op.create_table('likes',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interviewer_id'], ['interviewer.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'interviewer_id')
    )
    op.create_table('trolls',
    sa.Column('interviewer_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interviewer_id'], ['interviewer.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('interviewer_id', 'question_id')
    )
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('rol_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_foreign_key(None, 'user', 'question', ['question_id'], ['id'])
    op.create_foreign_key(None, 'user', 'rol', ['rol_id'], ['id'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'question_id')
    op.drop_column('user', 'rol_id')
    op.drop_column('user', 'username')
    op.drop_table('trolls')
    op.drop_table('likes')
    op.drop_table('dislikes')
    op.drop_table('question')
    op.drop_table('rol')
    op.drop_table('interviewer')
    op.drop_table('category')
    # ### end Alembic commands ###
