"""empty message

Revision ID: 5e197c3cb955
Revises: f39545d7f3d1
Create Date: 2022-11-21 18:37:11.585229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e197c3cb955'
down_revision = 'f39545d7f3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviewer', sa.Column('description', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviewer', 'description')
    # ### end Alembic commands ###
