"""empty message

Revision ID: f39545d7f3d1
Revises: 93b37e062a53
Create Date: 2022-11-21 18:05:53.799625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39545d7f3d1'
down_revision = '93b37e062a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'interviewer', ['name'])
    op.create_unique_constraint(None, 'rol', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'rol', type_='unique')
    op.drop_constraint(None, 'interviewer', type_='unique')
    # ### end Alembic commands ###
